# This is a GitHub Actions workflow for deploying Terraform configurations
name: 'Terraform GitHub Deploy'

# This workflow gets triggered on every push to the 'main' branch
on:
  push:
    branches:
      - main

# Define jobs to be run
jobs:
  terraform:
    # The job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # Define the steps to be executed in the job
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials from GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Setup Terraform with the specified version
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 6: Generate a Terraform plan
      - name: Terraform Plan
        run: terraform plan -var-file="environments/dev/lambda_all.tfvars" 

      # Step 7: Apply the Terraform plan
      - name: Terraform Apply
        run: terraform apply -var-file="environments/dev/lambda_all.tfvars" -auto-approve
